name: default

kind: pipeline
type: docker

steps:
- name: backend
  image: alpine
  commands:
  - echo Hello
  - echo Sleep for 30 seconds
  - sleep 30
  - echo Wake up now
  - sleep 5
  - echo Done
  
trigger:
  event:
  - cron
  cron:
  - 0 * * * *
